version: "3.7"

services:
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Australia/Perth
    volumes:
      - /mnt/sdb1/docker/bazarr/config:/config:rw
      - /mnt/sdb1/data/media:/data/media:rw
      - /etc/localtime:/etc/localtime:ro
