version: "3.2"
services:
  sabnzbd:
    container_name: sabnzbd
    image: cr.hotio.dev/hotio/sabnzbd:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/sdb/docker/sabnzbd/config:/config:rw
      - /mnt/sdb/data/usenet:/data/usenet:rw
