version: "3.7"

services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - /mnt/d/docker/radarr/config:/config:rw
      - /mnt/d/data:/data:rw
      - /etc/localtime:/etc/localtime:ro
