services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    ports:
      - "8096:8096"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Australia/Perth
    volumes:
      - /mnt/sdb1/docker/jellyfin/onfig:/config
      - /mnt/sdb1/docker/jellyfin/data:/data
      - /mnt/sdb1/data/media:/data/media
      - /etc/localtime:/etc/localtime:ro
