version: "3.7"

services:
  plex:
    container_name: plex
    image: ghcr.io/hotio/plex
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Australia/Perth
      - PLEX_CLAIM_TOKEN
      - PLEX_ADVERTISE_URL
      - PLEX_NO_AUTH_NETWORKS
      - PLEX_BETA_INSTALL=false
    volumes:
      - /mnt/sdb1/docker/plex/config:/config
      - /mnt/sdb1/docker/plex/transcode:/transcode
      - /mnt/sdb1/data/media:/data/media
      - /etc/localtime:/etc/localtime:ro
