version: "3.7"

services:
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - /mnt/sdb1/docker/sabnzbd/config:/config:rw
      - /mnt/sdb1/data/usenet:/data/usenet:rw
      - /etc/localtime:/etc/localtime:ro
